# Pandas

In [1]:
import pandas as pd

df = pd.read_csv("US500_30D_data.csv")

In [ ]:
# Why pandas
"""
Import data sets --> csv, exel, sql
Data cleansing  --> missing values, invalid values
Size mutibility  --> add and delet column and rows
Reshaping and pivotiong of datasets
Efficent manipulation and extraction
Statistical analyses """

In [ ]:
# Primary data structur --> 1. Series    - A one dimensional labeled homogeneouus array sizeimmutable.
#                           2. Dataframe - A two dimensional labeled size-muitable tabular structuree with potentially homogenously typed columns.
# Data structure are collection of data types that provide the bes way of organizing(values) in term of memory usage.

# Homogenous - same data type
# Hetrogenous - differnt data type

In [1]:
import pandas as pd # ---> alias pd

Series

In [5]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s.dtype

dtype('int64')

In [7]:
s.values

array([10, 20, 30, 40, 50])

In [40]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
s.size

5

In [42]:
s.name = "Calori"
print(s.name)

Calori

In [43]:
s

0    10
1    20
2    30
3    40
4    50
Name: Calori, dtype: int64

In [44]:
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Calori, dtype: int64

In [45]:
# Indexing

s[0:2] # start (include) : stop (exclude): step value (values to jump)

0    10
1    20
Name: Calori, dtype: int64

In [46]:
s[2:4]

2    30
3    40
Name: Calori, dtype: int64

In [47]:
# iloc --> Location based indexing

s.iloc[3]

np.int64(40)

In [48]:
s.iloc[[1,4,2]]

1    20
4    50
2    30
Name: Calori, dtype: int64

In [49]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]

In [50]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: Calori, dtype: int64

In [51]:
s["grapes"]

np.int64(30)

In [113]:
# loc --> lable based indexing
s.loc["orange"]

np.int64(40)

In [54]:
# In labe based indexing start as well as stop value both are included in the output.
s["banana": "orange"]

banana    20
grapes    30
orange    40
Name: Calori, dtype: int64

In [62]:
fruit_protein = {
     "Avacado" : 2.0,
     "Guava" : 2.6,
     "Blackbarry" : 2.0,
     "Orange" : 0.9,
     "Banana" : 1.1,
     "Apple" : 0.3,
     "Kiwi" : 1.1,
     "Pomegranate" : 1.7,
     "Mangoes" : 0.8,
     "Cherries" : 1.0
}

In [65]:
s2 = pd.Series(fruit_protein, name = "protein")
s2

Avacado        2.0
Guava          2.6
Blackbarry     2.0
Orange         0.9
Banana         1.1
Apple          0.3
Kiwi           1.1
Pomegranate    1.7
Mangoes        0.8
Cherries       1.0
Name: protein, dtype: float64

In [ ]:
# Conditional selecrtion

In [67]:
s2[s2 > 1]

Avacado        2.0
Guava          2.6
Blackbarry     2.0
Banana         1.1
Kiwi           1.1
Pomegranate    1.7
Name: protein, dtype: float64

In [68]:
# Logical Operator  --> And , OR, Not
# And --> If both the statement are true then only it will be true.
# OR --> If one the statement is true then it will return us true.

In [72]:
s2[(s2 > 0.5) & (s2 < 2)]

Orange         0.9
Banana         1.1
Kiwi           1.1
Pomegranate    1.7
Mangoes        0.8
Cherries       1.0
Name: protein, dtype: float64

In [ ]:
(s2 > 0.5) & (s2 < 2) # Return statement in true and false

Avacado        False
Guava          False
Blackbarry     False
Orange          True
Banana          True
Apple          False
Kiwi            True
Pomegranate     True
Mangoes         True
Cherries        True
Name: protein, dtype: bool

In [ ]:
s2[(s2 > 0.5) | (s2 < 2)] # or operation

Avacado        2.0
Guava          2.6
Blackbarry     2.0
Orange         0.9
Banana         1.1
Apple          0.3
Kiwi           1.1
Pomegranate    1.7
Mangoes        0.8
Cherries       1.0
Name: protein, dtype: float64

In [82]:
# Not operation
s2[~(s2>1)]

Orange      0.9
Apple       0.3
Cherries    1.0
Name: protein, dtype: float64

In [83]:
# Modefying

s2["Mangoes"] = 3

In [84]:
s2

Avacado        2.0
Guava          2.6
Blackbarry     2.0
Orange         0.9
Banana         1.1
Apple          0.3
Kiwi           5.0
Pomegranate    1.7
Mangoes        3.0
Cherries       1.0
mangoes        3.0
Name: protein, dtype: float64

In [85]:
s2["Kiwi"] = 5

In [81]:
s2

Avacado        2.0
Guava          2.6
Blackbarry     2.0
Orange         0.9
Banana         1.1
Apple          0.3
Kiwi           5.0
Pomegranate    1.7
Mangoes        3.0
Cherries       1.0
mangoes        3.0
Name: protein, dtype: float64

# Dataframe

In [97]:
import numpy as np
ser = pd.Series(['a'. np.nan, 1, np.nan, 2])
s.notnull().sum()

AttributeError: 'str' object has no attribute 'np'

In [2]:
# DataFrame :
import pandas as pd
import numpy as np

data = {
     "Nmae" : ["Alice", "Bob", "Charlie", "David", "Eva", "Alice"],
     "Age" : [25,30,35, np.nan,29, 25 ],
     "Department" : ["HR", "IT", "Finance", "IT", "HR", "HR"],
     "Salary" : [50000,60000,70000,62000,np.nan,50000]
}

In [3]:
df = pd.DataFrame(data)
df

      Nmae   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eva  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [4]:
df.head()

      Nmae   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eva  29.0         HR      NaN

In [5]:
df.tail(3)

    Nmae   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eva  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [6]:
df.iloc[1:3]

      Nmae   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [7]:
df.iloc[1:5]

      Nmae   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eva  29.0         HR      NaN

In [19]:
df.loc[1:3,["Age","Department"]]
#df.loc[1:3,"Age":"Department"]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [27]:
# loc and iloc

df.iloc[1:5, :2]

      Nmae   Age
1      Bob  30.0
2  Charlie  35.0
3    David   NaN
4      Eva  29.0

In [32]:
# iloc --> Location based indexing
df.iloc[1:4:2]

    Nmae   Age Department   Salary
1    Bob  30.0         IT  60000.0
3  David   NaN         IT  62000.0

In [11]:
df

      Nmae   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eva  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [36]:
#position based indexing
df.iloc[1:3, :1]

      Nmae
1      Bob
2  Charlie

In [13]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [14]:
df[["Age","Salary"]]

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  35.0  70000.0
3   NaN  62000.0
4  29.0      NaN
5  25.0  50000.0

In [254]:
df.drop("Salary", axis= 1) # inplace = True --> if you want to delet from orignal dataset

      Nmae   Age Department
0    Alice  25.0         HR
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT
4      Eva  29.0         HR
5    Alice  25.0         HR

In [255]:
df

      Nmae   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eva  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [256]:
df.shape

(6, 4)

In [257]:
df.dtypes

Nmae           object
Age           float64
Department     object
Salary        float64
dtype: object

In [258]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nmae        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [259]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [260]:
# Brodcasting
# Increasing Salary by 5000

df["Salary"] = df["Salary"] + 5000

In [261]:
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [262]:
# Increasing age by + one

df["Age"] = df["Age"] + 1

In [263]:
df["Age"]

0    26.0
1    31.0
2    36.0
3     NaN
4    30.0
5    26.0
Name: Age, dtype: float64

In [264]:
# Rename a data

df.rename(columns= {"Department": "Dept"}, inplace= True)

In [265]:
df.head()

      Nmae   Age     Dept   Salary
0    Alice  26.0       HR  55000.0
1      Bob  31.0       IT  65000.0
2  Charlie  36.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eva  30.0       HR      NaN

In [266]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [267]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [268]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [269]:
# Creating new cooumn

df["Prometed Salary"] = df["Salary"] * 10

In [270]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN
5    Alice  26.0       HR  55000.0         550000.0

In [271]:
# Data cleaning

In [272]:
df.isnull().sum()

Nmae               0
Age                1
Dept               0
Salary             1
Prometed Salary    1
dtype: int64

In [273]:
# To completly drop this null values

In [274]:
df.dropna()

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
5    Alice  26.0       HR  55000.0         550000.0

In [275]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN
5    Alice  26.0       HR  55000.0         550000.0

In [276]:
df.dropna(how= "any") # any row has any null values

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
5    Alice  26.0       HR  55000.0         550000.0

In [277]:
df.dropna(how= "all") # IF all the raw has null values

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN
5    Alice  26.0       HR  55000.0         550000.0

In [278]:
# TO fill those missing values.

In [279]:
df.fillna(0)

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   0.0       IT  67000.0         670000.0
4      Eva  30.0       HR      0.0              0.0
5    Alice  26.0       HR  55000.0         550000.0

In [280]:
df["Age"].fillna(df["Age"].mean()) # replace all the missing value with mean

0    26.0
1    31.0
2    36.0
3    29.8
4    30.0
5    26.0
Name: Age, dtype: float64

In [281]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [282]:
# fillna we have two things --> Forward fill
                      #     --> Backword fill

In [283]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1      Bob  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN
5    Alice  26.0       HR  55000.0         550000.0

In [284]:
# Forward fill
df["Age"].fillna(method = "ffill")

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\1763736310.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    26.0
1    31.0
2    36.0
3    36.0
4    30.0
5    26.0
Name: Age, dtype: float64

In [285]:
# Backwoed fill
df["Age"].fillna(method = "bfill")

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\1542259515.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    26.0
1    31.0
2    36.0
3    30.0
4    30.0
5    26.0
Name: Age, dtype: float64

In [286]:
# Replace a particular value

df["Nmae"].replace(["Charlie", "Rose"])

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\2539731917.py:3: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df["Nmae"].replace(["Charlie", "Rose"])

0    Alice
1      Bob
2      Bob
3    David
4      Eva
5    Alice
Name: Nmae, dtype: object

In [287]:
df["Nmae"] = df["Nmae"].replace("Bob","Rose")
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1     Rose  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN
5    Alice  26.0       HR  55000.0         550000.0

In [288]:
# How to deal with duplicate value

In [289]:
df_dup = df.duplicated(keep = "first")
df_dup

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [290]:
# Removing duplicate values
df = df.drop_duplicates()

In [291]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1     Rose  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eva  30.0       HR      NaN              NaN

In [292]:
# Invalid values
# Lambda

df["Prometed Salary"] = df["Prometed Salary"].apply(lambda x: x/10 if x > 650000 else x)

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\487384240.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Prometed Salary"] = df["Prometed Salary"].apply(lambda x: x/10 if x > 650000 else x)

In [293]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1     Rose  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eva  30.0       HR      NaN              NaN

In [294]:
# Spliting strings 
name = "Alice Fernandes"
df[["first_name","last_name"]] = df["name"].str.split(" ")

KeyError: 'name'

In [295]:
# Apply and lamda
def multiplying_age(x):
     return x*2
df["Age"] = df["Age"].apply(multiplying_age)

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\1877337966.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [296]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  52.0       HR  55000.0         550000.0
1     Rose  62.0       IT  65000.0         650000.0
2  Charlie  72.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eva  60.0       HR      NaN              NaN

In [297]:
df["Age"] = df["Age"].apply(lambda x: x/2)

C:\Users\laptop\AppData\Local\Temp\ipykernel_16344\1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [298]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1     Rose  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eva  30.0       HR      NaN              NaN

In [299]:
# Joins and merges 
# joins --> left,right,outer,inner
# merge --> inner joins


department_info = {
     "Department" : ["HR", "IT", "Finance"],
     "Location" : ["New york", "Sanfrancisco", "Chicago"],
     "Manager" : ["Laura", "Steav", "Nina"]
}
df2 = pd.DataFrame(department_info)

In [300]:
df2

  Department      Location Manager
0         HR      New york   Laura
1         IT  Sanfrancisco   Steav
2    Finance       Chicago    Nina

In [301]:
df

      Nmae   Age     Dept   Salary  Prometed Salary
0    Alice  26.0       HR  55000.0         550000.0
1     Rose  31.0       IT  65000.0         650000.0
2  Charlie  36.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eva  30.0       HR      NaN              NaN

In [ ]:
# Concatination
# Row wise
pd.concat([df,df2])

,Nmae,Age,Dept,Salary,Prometed Salary,Department,Location,Manager
0,Alice,26.0,HR,55000.0,550000.0,NaN,NaN,NaN
1,Rose,31.0,IT,65000.0,650000.0,NaN,NaN,NaN
2,Charlie,36.0,Finance,75000.0,75000.0,NaN,NaN,NaN
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eva,30.0,HR,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New york,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,Sanfrancisco,Steav
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [305]:
# Column wise
pd.concat([df,df2], axis= 1)

,Nmae,Age,Dept,Salary,Prometed Salary,Department,Location,Manager
0,Alice,26.0,HR,55000.0,550000.0,HR,New york,Laura
1,Rose,31.0,IT,65000.0,650000.0,IT,Sanfrancisco,Steav
2,Charlie,36.0,Finance,75000.0,75000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eva,30.0,HR,NaN,NaN,NaN,NaN,NaN

In [308]:
pd.merge(df,df2, on = "Age")

KeyError: 'Age'

In [309]:
# importing files

data = pd.read_csv("US500_30D_data")

In [310]:
data.head()

,time,open,high,low,close,tick_volume,spread,real_volume
0,2025-11-06 15:33:00,6768.26,6768.28,6763.75,6764.47,513,0,0
1,2025-11-06 15:34:00,6764.61,6765.83,6763.68,6765.18,364,0,0
2,2025-11-06 15:35:00,6765.31,6765.33,6760.42,6762.08,438,0,0
3,2025-11-06 15:36:00,6762.31,6762.81,6753.22,6753.46,526,0,0
4,2025-11-06 15:37:00,6753.62,6754.59,6747.00,6747.47,593,0,0

In [311]:
data.shape

(28220, 8)

In [312]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28220 entries, 0 to 28219
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   time         28220 non-null  object
 1   open         28220 non-null  float64
 2   high         28220 non-null  float64
 3   low          28220 non-null  float64
 4   close        28220 non-null  float64
 5   tick_volume  28220 non-null  int64
 6   spread       28220 non-null  int64
 7   real_volume  28220 non-null  int64
dtypes: float64(4), int64(3), object(1)
memory usage: 1.7+ MB

In [319]:
data["date"] = pd.to_datetime(df["date"])

KeyError: 'date'

In [317]:
data.columns

Index(['time', 'open', 'high', 'low', 'close', 'tick_volume', 'spread',
       'real_volume'],
      dtype='object')